Primer commit del proyecto: añadir archivo.txt
entornos2324/trabajo2324 pull request #15
Opened 2024-05-07 17:57 UTC by camosama94

2024-05-07 18:05 UTC, entornos2324 requested changes
Debes cambiar el fichero y quitar el espacio en blanco que sobra

2024-05-07 18:06 UTC, entornos2324 requested changes
Además el nombre del archivo no es correcto. Es fichero.txt

2024-05-08 15:38 UTC, camosama94 commented
Correcciones realizadas

2024-05-08 18:59 UTC, entornos2324 commented
Perfecto!!!!!!!!!! Lo mejor de esto es que antes de efectuar cambios, se revisa el código y si está todo bien, se hace MERGE con el repositorio original :D

2024-05-08 18:59 UTC, merged